blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/product-on-purpose/pm-skills/discussions
    about: Please ask questions in GitHub Discussions
